### ISSUE TITLE
Write a PySpark WordCount program

### ISSUE THREAD

**Issue by AshokKumarChoppadandi** [AshokKumarChoppadandi/PySparkExamples#4]
Write a PySpark WordCount program, test in PySpark shell and finally test with Spark Submit.

Attach screenshots for reference.

**Comment by laxmankusuma** [comment]
completed word count program and committed code .

**Comment by laxmankusuma** [comment]
Hi @AshokKumarChoppadandi  ,
im unable to this , please help on this.
![image](https://user-images.githubusercontent.com/17021017/69828143-a2fe4080-1240-11ea-89ba-9458ccd2d03f.png)
